let dictated = [
	// 'let name one equals variable one',
	// 'variable age of equals 64',
	// 'constant addition equals name plus age percentage 64 by 24',
	// 'let array equals list name one comma 2',
	// 'close',
	// 'array two equals list',
	// ' one comma tolet',
	// 'object name value 2',
	// 'name value 2',
	// 'close',
	// 'close',
	// '12',
	// 'close',
	// 'constant name equals object name value string sivanesh',
	// 'arg value list 1 comma two',
	// // 'hobbies value list string cricket comma batminton comma true comma object',
	// 'close',
	// 'close'
	// 'let name equals list 1 comma two',
	// 'object try value string workd',
	// 'name world value 12',
	// 'close',
	// '12 comma string right',
	// 'close',
	// 'constant name equals arrow function'
	// 'comment its a comment',
	// 'let name equals 76',
	// 'comment paragraph',
	// 'let name equals 76',
	// 'hello world',
	// 'here its gonna be very big comment',
	// 'close',
	// 'let name equals string a'

	// 'print string hello world',
	// 'print 12',
	// 'print true',
	// 'print false',
	// 'let name equals string hello world',
	// 'variable name dot substring of string new comma 123',
	// 'string dot char code at',
	// 'string dot length',
	// 'string dot index of string is',
	// 'let name equals arrow function',
	// 'name one equals string dot last index of string is',
	// 'name two equals string dot character code at of 0',
	// 'constant name three equals string dot character at of 0',
	// 'variable name vada equals string dot to lower case of',
	'function method one',
	'print string hello world',
	'close',
	'call method one of true comma 2 comma string hello world',
	'let age equals a b equal to 27 minus equal to string hello triple equal to name bitwise and a plus ageplus',
	'let age equals 1 bitwise and 2',
	'let age equals 1 triple equal to name'
	// 'let name equals 5 plus name minus as'
];
